DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS recipes CASCADE;

DROP TABLE IF EXISTS reviews CASCADE;

DROP TABLE IF EXISTS ingredients CASCADE;

DROP TABLE IF EXISTS recipes_ingredients CASCADE;

DROP TABLE IF EXISTS tags_types CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP TABLE IF EXISTS recipes_tags CASCADE;