// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Recipe struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	Synopsis   string `json:"synopsis"`
	Time       int32  `json:"time"`
	Difficulty int32  `json:"difficulty"`
}

type RecipesIngredient struct {
	RecipeID     int32       `json:"recipe_id"`
	IngredientID int32       `json:"ingredient_id"`
	Amount       int32       `json:"amount"`
	Unit         pgtype.Int4 `json:"unit"`
}

type RecipesTag struct {
	RecipeID int32 `json:"recipe_id"`
	TagID    int32 `json:"tag_id"`
}

type Review struct {
	ID          int32 `json:"id"`
	RecipeID    int32 `json:"recipe_id"`
	UserID      int32 `json:"user_id"`
	ReviewScore int32 `json:"review_score"`
}

type Tag struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	TypeID int32  `json:"type_id"`
}

type TagsType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID          int32            `json:"id"`
	Username    string           `json:"username"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Passwdhash  string           `json:"passwdhash"`
	Email       string           `json:"email"`
	Name        pgtype.Text      `json:"name"`
	Surname     pgtype.Text      `json:"surname"`
	PhoneNumber string           `json:"phone_number"`
	Age         int32            `json:"age"`
	Sex         string           `json:"sex"`
	Weight      pgtype.Int4      `json:"weight"`
	Height      pgtype.Int4      `json:"height"`
	Bmi         pgtype.Int4      `json:"bmi"`
}
