INSERT INTO tags_types (name)
VALUES
  ('Dieta'),
  ('Region'),
  ('Rodzaj'),
  ('Alergie'),
  ('Składniki_odżywcze'),
  ('Inne');

INSERT INTO tags (name, type_id) VALUES ('wegetariańska', 1);
INSERT INTO tags (name, type_id) VALUES ('vegańska', 1);
INSERT INTO tags (name, type_id) VALUES ('mięsna', 1);
INSERT INTO tags (name, type_id) VALUES ('jarska', 1);
INSERT INTO tags (name, type_id) VALUES ('keto', 1);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia europejska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia azjatycka', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia afrykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia północnoamerykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia latynoamerykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia śródziemnomorska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia bliskowschodnia', 2);
INSERT INTO tags (name, type_id) VALUES ('Kuchnia oceaniczna', 2);
INSERT INTO tags (name, type_id) VALUES ('Polska', 2);
INSERT INTO tags (name, type_id) VALUES ('Włoska', 2);
INSERT INTO tags (name, type_id) VALUES ('Francuska', 2);
INSERT INTO tags (name, type_id) VALUES ('Niemiecka', 2);
INSERT INTO tags (name, type_id) VALUES ('Hiszpańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Portugalska', 2);
INSERT INTO tags (name, type_id) VALUES ('Grecka', 2);
INSERT INTO tags (name, type_id) VALUES ('Rosyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Skandynawska', 2);
INSERT INTO tags (name, type_id) VALUES ('Brytyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Irlandzka', 2);
INSERT INTO tags (name, type_id) VALUES ('Holenderska', 2);
INSERT INTO tags (name, type_id) VALUES ('Belgijska', 2);
INSERT INTO tags (name, type_id) VALUES ('Czeska', 2);
INSERT INTO tags (name, type_id) VALUES ('Węgierska', 2);
INSERT INTO tags (name, type_id) VALUES ('Austriacka', 2);
INSERT INTO tags (name, type_id) VALUES ('Szwajcarska', 2);
INSERT INTO tags (name, type_id) VALUES ('Chorwacka', 2);
INSERT INTO tags (name, type_id) VALUES ('Bałkańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Turecka', 2);
INSERT INTO tags (name, type_id) VALUES ('Libańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Izraelska', 2);
INSERT INTO tags (name, type_id) VALUES ('Perska', 2);
INSERT INTO tags (name, type_id) VALUES ('Arabska', 2);
INSERT INTO tags (name, type_id) VALUES ('Indyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Pakistańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Bangladeska', 2);
INSERT INTO tags (name, type_id) VALUES ('Nepalska', 2);
INSERT INTO tags (name, type_id) VALUES ('Sri Lanka', 2);
INSERT INTO tags (name, type_id) VALUES ('Chińska', 2);
INSERT INTO tags (name, type_id) VALUES ('Japońska', 2);
INSERT INTO tags (name, type_id) VALUES ('Koreańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Wietnamska', 2);
INSERT INTO tags (name, type_id) VALUES ('Tajska', 2);
INSERT INTO tags (name, type_id) VALUES ('Malezyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Indonezyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Filipińska', 2);
INSERT INTO tags (name, type_id) VALUES ('Australijska', 2);
INSERT INTO tags (name, type_id) VALUES ('Nowozelandzka', 2);
INSERT INTO tags (name, type_id) VALUES ('Amerykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kanadyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Meksykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Środkowoamerykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Karaibska', 2);
INSERT INTO tags (name, type_id) VALUES ('Brazylianska', 2);
INSERT INTO tags (name, type_id) VALUES ('Argentynska', 2);
INSERT INTO tags (name, type_id) VALUES ('Chilijska', 2);
INSERT INTO tags (name, type_id) VALUES ('Peruwiańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Kolumbijska', 2);
INSERT INTO tags (name, type_id) VALUES ('Wenezuelska', 2);
INSERT INTO tags (name, type_id) VALUES ('Etiopska', 2);
INSERT INTO tags (name, type_id) VALUES ('Marokańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Południowoafrykańska', 2);
INSERT INTO tags (name, type_id) VALUES ('Nigeryjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Egipska', 2);
INSERT INTO tags (name, type_id) VALUES ('Tunezyjska', 2);
INSERT INTO tags (name, type_id) VALUES ('Przystawki i przekąski', 3);
INSERT INTO tags (name, type_id) VALUES ('Zupy', 3);
INSERT INTO tags (name, type_id) VALUES ('Sałatki', 3);
INSERT INTO tags (name, type_id) VALUES ('Kotlety', 3);
INSERT INTO tags (name, type_id) VALUES ('Tarty/Pizza', 3);
INSERT INTO tags (name, type_id) VALUES ('Placki', 3);
INSERT INTO tags (name, type_id) VALUES ('Warzywa', 3);
INSERT INTO tags (name, type_id) VALUES ('Ryż', 3);
INSERT INTO tags (name, type_id) VALUES ('Dania jednogarnkowe', 3);
INSERT INTO tags (name, type_id) VALUES ('Makarony', 3);
INSERT INTO tags (name, type_id) VALUES ('Grillowane', 3);
INSERT INTO tags (name, type_id) VALUES ('Smażone', 3);
INSERT INTO tags (name, type_id) VALUES ('na parze', 3);
INSERT INTO tags (name, type_id) VALUES ('Pieczone', 3);
INSERT INTO tags (name, type_id) VALUES ('Duszone', 3);
INSERT INTO tags (name, type_id) VALUES ('Kasze', 3);
INSERT INTO tags (name, type_id) VALUES ('Mączne', 3);
INSERT INTO tags (name, type_id) VALUES ('Sałatki', 3);
INSERT INTO tags (name, type_id) VALUES ('Ryby', 3);
INSERT INTO tags (name, type_id) VALUES ('Fast food / Street food', 3);
INSERT INTO tags (name, type_id) VALUES ('Desery', 3);
INSERT INTO tags (name, type_id) VALUES ('Ciasta i wypieki', 3);
INSERT INTO tags (name, type_id) VALUES ('Puddingi i kremy', 3);
INSERT INTO tags (name, type_id) VALUES ('Napoje bezalkoholowe', 3);
INSERT INTO tags (name, type_id) VALUES ('Drinki', 3);
INSERT INTO tags (name, type_id) VALUES ('Węglowodany', 5);
INSERT INTO tags (name, type_id) VALUES ('Białka', 5);
INSERT INTO tags (name, type_id) VALUES ('Kwasy tłuszczowe nasycone', 5);
INSERT INTO tags (name, type_id) VALUES ('Kwasy tłuszczowe nienasycone', 5);
INSERT INTO tags (name, type_id) VALUES ('Cukry proste', 5);
INSERT INTO tags (name, type_id) VALUES ('Cukry złożone', 5);
INSERT INTO tags (name, type_id) VALUES ('Błonnik', 5);
INSERT INTO tags (name, type_id) VALUES ('Witaminy(można dokładniej)', 5);
INSERT INTO tags (name, type_id) VALUES ('Wapń', 5);
INSERT INTO tags (name, type_id) VALUES ('Żelazo', 5);
INSERT INTO tags (name, type_id) VALUES ('Magnez', 5);
INSERT INTO tags (name, type_id) VALUES ('Potas', 5);
INSERT INTO tags (name, type_id) VALUES ('Sód', 5);
INSERT INTO tags (name, type_id) VALUES ('Cynk', 5);
INSERT INTO tags (name, type_id) VALUES ('Cholesterol', 5);
INSERT INTO tags (name, type_id) VALUES ('Gluten(Zboże)', 4);
INSERT INTO tags (name, type_id) VALUES ('Jajka', 4);
INSERT INTO tags (name, type_id) VALUES ('Produkty mleczne(dairy)', 4);
INSERT INTO tags (name, type_id) VALUES ('Ryby i owoce morza', 4);
INSERT INTO tags (name, type_id) VALUES ('Orzechy', 4);
INSERT INTO tags (name, type_id) VALUES ('Soja', 4);
INSERT INTO tags (name, type_id) VALUES ('Sezam', 4);
INSERT INTO tags (name, type_id) VALUES ('Gorczyca', 4);
INSERT INTO tags (name, type_id) VALUES ('Lupina', 4);
INSERT INTO tags (name, type_id) VALUES ('Seler', 4);
INSERT INTO tags (name, type_id) VALUES ('Siarczyny i dodatki sztuczne(np. barwniki)', 4);
INSERT INTO tags (name, type_id) VALUES ('lekkostrawne', 6);
INSERT INTO tags (name, type_id) VALUES ('tanie', 6);
